# Generated by Django 6.0 on 2026-01-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='title',
        ),
    ]
